---
abstract: 'Build REST-inspired routing tables'
author:
  - 'David E. Wheeler <david@kineticode.com>'
build_requires:
  Module::Build: 0.30
  Test::More: 0.70
configure_requires:
  Module::Build: 0.30
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Router-Resource
provides:
  Router::Resource:
    file: lib/Router/Resource.pm
    version: 0.11
recommends:
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.06
requires:
  Router::Simple: 0.07
  Sub::Exporter: 0
  perl: 5.008001
resources:
  bugtracker: http://github.com/theory/router-resource/issues/
  homepage: http://search.cpan.org/dist/Router-Resource/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/router-resource/tree/
version: 0.11
